import puppeteer from 'puppeteer';
import prisma from '../config/prisma';

export async function generateInvoicePDF(challanId: number): Promise<Buffer> {
  const challan = await prisma.salesChallan.findUnique({
    where: { id: challanId },
    include: { items: true, createdBy: { select: { name: true } } },
  });

  if (!challan) throw new Error('CHALLAN_NOT_FOUND');
  if (challan.status !== 'CONFIRMED') throw new Error('ONLY_CONFIRMED_CHALLANS_CAN_BE_EXPORTED');

  const html = buildInvoiceHTML(challan);

  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    const pdf = await page.pdf({ format: 'A4', printBackground: true, margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' } });
    return Buffer.from(pdf);
  } finally {
    await browser.close();
  }
}

function buildInvoiceHTML(challan: any): string {
  const date = new Date(challan.createdAt).toLocaleDateString('en-IN', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  const rows = challan.items.map((item: any, i: number) => `
    <tr>
      <td>${i + 1}</td>
      <td>${item.productNameSnapshot}</td>
      <td>${item.skuSnapshot}</td>
      <td style="text-align:right">${item.quantity}</td>
      <td style="text-align:right">₹${Number(item.unitPrice).toLocaleString('en-IN')}</td>
      <td style="text-align:right">₹${Number(item.totalPrice).toLocaleString('en-IN')}</td>
    </tr>
  `).join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Arial, sans-serif; font-size: 13px; color: #1a1a1a; }
        .header { background: #051F20; color: #DAF1DE; padding: 24px; display: flex; justify-content: space-between; align-items: center; }
        .company-name { font-size: 22px; font-weight: bold; }
        .company-sub { font-size: 12px; opacity: 0.8; margin-top: 4px; }
        .invoice-meta { text-align: right; }
        .invoice-meta h2 { font-size: 18px; margin-bottom: 4px; }
        .section { padding: 20px 0; border-bottom: 1px solid #e0e0e0; }
        .grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; padding: 20px 0; }
        .label { font-size: 11px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 4px; }
        .value { font-weight: 600; font-size: 14px; }
        .value-sub { font-size: 12px; color: #444; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        thead tr { background: #051F20; color: #DAF1DE; }
        thead th { padding: 10px 12px; text-align: left; font-size: 12px; }
        tbody tr:nth-child(even) { background: #f8fdf9; }
        tbody td { padding: 10px 12px; border-bottom: 1px solid #e8f4ea; }
        .total-row { background: #235347 !important; color: white; font-weight: bold; }
        .total-row td { padding: 12px; border: none !important; }
        .footer { margin-top: 40px; text-align: center; font-size: 11px; color: #888; }
        .status-badge { display: inline-block; background: #d1fae5; color: #065f46; padding: 4px 10px; border-radius: 4px; font-size: 11px; font-weight: bold; }
      </style>
    </head>
    <body>
      <div class="header">
        <div>
          <div class="company-name">AgriDist Operations</div>
          <div class="company-sub">Wholesale & Distribution Company</div>
        </div>
        <div class="invoice-meta">
          <h2>TAX INVOICE</h2>
          <div style="opacity:0.8; font-size:12px">Invoice #: INV-${challan.id.toString().padStart(6, '0')}</div>
          <div style="opacity:0.8; font-size:12px">Challan: ${challan.challanNumber}</div>
          <div style="opacity:0.8; font-size:12px">Date: ${date}</div>
        </div>
      </div>

      <div class="grid-2">
        <div>
          <div class="label">Bill To</div>
          <div class="value">${challan.customerNameSnapshot}</div>
          <div class="value-sub">${challan.businessNameSnapshot}</div>
          <div class="value-sub">Mobile: ${challan.mobileSnapshot}</div>
          ${challan.gstNumberSnapshot ? `<div class="value-sub">GST: ${challan.gstNumberSnapshot}</div>` : ''}
        </div>
        <div style="text-align:right">
          <div class="label">Status</div>
          <div class="status-badge">CONFIRMED</div>
          <div style="margin-top:8px">
            <div class="label">Generated By</div>
            <div class="value-sub">${challan.createdBy?.name || 'System'}</div>
          </div>
        </div>
      </div>

      <table>
        <thead>
          <tr>
            <th>#</th>
            <th>Product</th>
            <th>SKU</th>
            <th style="text-align:right">Qty</th>
            <th style="text-align:right">Unit Price</th>
            <th style="text-align:right">Total</th>
          </tr>
        </thead>
        <tbody>
          ${rows}
          <tr class="total-row">
            <td colspan="3">Total</td>
            <td style="text-align:right">${challan.totalQuantity} units</td>
            <td></td>
            <td style="text-align:right">₹${Number(challan.totalAmount).toLocaleString('en-IN')}</td>
          </tr>
        </tbody>
      </table>

      <div class="footer">
        <p>This is a computer-generated invoice. No signature required.</p>
        <p style="margin-top:4px">AgriDist Operations — Internal ERP System</p>
      </div>
    </body>
    </html>
  `;
}
